name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    name: Check code and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: uv sync

      - name: Run ruff
        run: uv run ruff check --no-fix

      - name: Run basedpyright
        run: uv run basedpyright

      - name: Run pytest (non-e2e)
        run: uv run pytest

  test-release:
    name: TestPyPI Release
    needs: [qa]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Publish to Test PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: uv publish --index testpypi
