name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pypi:
    name: PyPI Release
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Read version from local file
        id: version
        run: |
          VERSION=$(grep '__version__' src/boox/__init__.py | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare local version to pushed tag
        run: |
          VERSION="${{ steps.version.outputs.version }}
          TAG=${GITHUB_REF#refs/tags/v}
          if [[ "$TAG" != "$VERSION" ]]; then
            echo "Tag version ($TAG) does not match local file's version ($VERSION)"
            exit 1
          fi

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: uv sync

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always
