name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: PyPI Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: uv sync --no-dev --extra release

      - name: Build package
        run: uv run python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: uvx twine upload dist/*
